import { supabase } from './supabase';
import type { AvatarState, Item, Student } from './types';

export interface RaidGuest { id:string; roomCode:string; nickname:string; joinOrder:number; avatarState:AvatarState; items:Item[]; createdAt:string; updatedAt:string }
const enabled=!!process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=(code:string)=>`ssaemraid_guests_${code.toUpperCase()}`;
const toStudent=(g:RaidGuest):Student=>({id:g.id,classId:g.roomCode,attendanceNumber:g.joinOrder,nickname:g.nickname,score:0,coins:0,items:g.items||[],avatarId:'raid-random',avatarState:g.avatarState,roomDecorations:[]});
export function raidGuestToStudent(g:RaidGuest){return toStudent(g)}
export async function listRaidGuests(roomCode:string):Promise<RaidGuest[]>{ const code=roomCode.toUpperCase(); if(enabled){const {data,error}=await supabase.from('raid_guests').select('*').eq('room_code',code).order('join_order'); if(!error)return (data||[]).map((r:any)=>({id:r.id,roomCode:r.room_code,nickname:r.nickname,joinOrder:r.join_order,avatarState:r.avatar_state,items:r.items||[],createdAt:r.created_at,updatedAt:r.updated_at}));} if(typeof window==='undefined')return []; return JSON.parse(localStorage.getItem(key(code))||'[]'); }
export async function createRaidGuest(roomCode:string,nickname:string,avatarState:AvatarState,items:Item[]):Promise<RaidGuest>{const code=roomCode.toUpperCase(); const existing=await listRaidGuests(code); const g:RaidGuest={id:crypto.randomUUID(),roomCode:code,nickname:nickname.trim(),joinOrder:(existing.reduce((m,x)=>Math.max(m,x.joinOrder),0)+1),avatarState,items,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; if(enabled){const {data,error}=await supabase.from('raid_guests').insert({id:g.id,room_code:code,nickname:g.nickname,join_order:g.joinOrder,avatar_state:g.avatarState,items:g.items}).select().single(); if(!error)return {...g,id:data.id}; throw new Error(error.message);} localStorage.setItem(key(code),JSON.stringify([...existing,g])); return g;}
export async function updateRaidGuest(g:RaidGuest){g.updatedAt=new Date().toISOString(); if(enabled){const {error}=await supabase.from('raid_guests').update({nickname:g.nickname,avatar_state:g.avatarState,items:g.items,updated_at:g.updatedAt}).eq('id',g.id); if(error)throw new Error(error.message); return;} const all=await listRaidGuests(g.roomCode); localStorage.setItem(key(g.roomCode),JSON.stringify(all.map(x=>x.id===g.id?g:x)));}
export async function deleteRaidGuest(id:string,roomCode:string){if(enabled){await supabase.from('raid_guests').delete().eq('id',id);return;} const all=await listRaidGuests(roomCode);localStorage.setItem(key(roomCode),JSON.stringify(all.filter(x=>x.id!==id)));}
export function saveRaidGuestSession(g:RaidGuest){sessionStorage.setItem('ssaemraid_guest',JSON.stringify(g));}
export function getRaidGuestSession():RaidGuest|null{if(typeof window==='undefined')return null;try{return JSON.parse(sessionStorage.getItem('ssaemraid_guest')||'null')}catch{return null}}
